ruby_version: 3.2
fix: true
parallel: true
ignore:
  - test/**/*
  - examples/**/*
  - myapp/**/*
  - 'lib/sidekiq/defer/**/*':
    - Style/MissingRespondToMissing
  - 'lib/**/*':
    - Lint/RescueException
    - Security/YAMLLoad
    - Style/GlobalVars
